### ISSUE TITLE
Mismatch in piqi_rpc_resource.erl

### ISSUE THREAD

**Issue by ghost** [spilgames/piqi-rpc#13]
piqi_rpc_resource.erl:57: The pattern {'error', {Code, Message, Req4}} can never match the type {'error',{415,<<_:176>>},cowboy_req:req()}

cc @yfyf 

The return value generated by validate_format() does not match highlighted case clause.

https://github.com/spilgames/piqi-rpc/blob/spil/src/piqi_rpc_resource.erl#L57
https://github.com/spilgames/piqi-rpc/blob/spil/src/piqi_rpc_resource.erl#L199

**Comment by yfyf** [comment]
Closed via d03b196fa5414ab5baa2129b24d4e7c5d900a312
